//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COINNP.Client.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COINNP.Client.ResourceFiles.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize object.
        /// </summary>
        internal static string ERR_Deserialization_Failed {
            get {
                return ResourceManager.GetString("ERR_Deserialization_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error invoking messagehandler.
        /// </summary>
        internal static string ERR_Invoking_MessageHandler {
            get {
                return ResourceManager.GetString("ERR_Invoking_MessageHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error invoking OnFinalDisconnect.
        /// </summary>
        internal static string ERR_Invoking_OnFinalDisconnect {
            get {
                return ResourceManager.GetString("ERR_Invoking_OnFinalDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener already in use.
        /// </summary>
        internal static string ERR_Listener_Already_In_Use {
            get {
                return ResourceManager.GetString("ERR_Listener_Already_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messagetype &apos;{0}&apos; is not implemented.
        /// </summary>
        internal static string ERR_Messagetype_Not_Implemented {
            get {
                return ResourceManager.GetString("ERR_Messagetype_Not_Implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to serialize object.
        /// </summary>
        internal static string ERR_Serialization_Failed {
            get {
                return ResourceManager.GetString("ERR_Serialization_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is an unknown value for enum type {1}.
        /// </summary>
        internal static string ERR_Unknown_Enum_Value {
            get {
                return ResourceManager.GetString("ERR_Unknown_Enum_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keepalive.
        /// </summary>
        internal static string EVT_Keepalive {
            get {
                return ResourceManager.GetString("EVT_Keepalive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string EVT_OnException {
            get {
                return ResourceManager.GetString("EVT_OnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string EVT_OnFinalDisconnect {
            get {
                return ResourceManager.GetString("EVT_OnFinalDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown message received. ID: &apos;{0}&quot;, Content: &apos;{1}&apos;.
        /// </summary>
        internal static string EVT_OnUnknownMessage {
            get {
                return ResourceManager.GetString("EVT_OnUnknownMessage", resourceCulture);
            }
        }
    }
}
